[85ztqdvce] add QR view controller
startmobile-kz/indrop.kz pull request #42
Opened 2023-08-15 18:31 UTC by zssyrymbet

Task-link: https://app.clickup.com/t/85ztqdvce

- added new icons and fonts
- added type system for button
- added QR view controller

2023-08-16 03:02 UTC, zssyrymbet commented
<img width="400" alt="Снимок экрана 2023-08-16 в 09 02 45" src="https://github.com/startmobile-kz/indrop.kz/assets/55020413/57145b95-6b30-42fa-8a98-8d0601d10832">

2023-08-16 04:33 UTC, damiraliyev commented on indrop/QR/QRViewController.swift
> +    private lazy var qrButton: UIButton = {
наверное лучше назвать shareButton

2023-08-16 04:36 UTC, damiraliyev commented
супер работа✊✊✊

2023-08-16 05:41 UTC, zssyrymbet commented
@damiraliyev Исправила все замечания, спасибо

2023-08-16 13:49 UTC, aitemr requested changes
нужно поправить на SE

2023-08-17 12:51 UTC, aitemr approved these changes

2023-08-17 12:51 UTC, aitemr approved these changes

2023-08-17 12:51 UTC, merged